apiVersion: v1
kind: Namespace
metadata:
  name: broadcast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broadcast
  name: broadcast
  namespace: broadcast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcast
  strategy: {}
  template:
    metadata:
      labels:
        app: broadcast
    spec:
      containers:
        - image: 244112418223.dkr.ecr.ap-east-1.amazonaws.com/mf2-tco-whatsapp:broadcast
          name: broadcast
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: broadcast-svc
  labels:
    run: broadcast-svc
  namespace: broadcast
spec:
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
      protocol: TCP
  selector:
    app: broadcast
  type: NodePort
