apiVersion: v1
kind: Namespace
metadata:
  name: message-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: message-server
  name: message-server
  namespace: message-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-server
  strategy: {}
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
        - image: 244112418223.dkr.ecr.ap-east-1.amazonaws.com/mf2-tco-whatsapp:message-module
          name: message-server
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: message-server
  labels:
    run: message-server
  namespace: message-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: message-server
  type: NodePort
